import { Afacad } from 'next/font/google'
import "./globals.css";

const font = Afacad({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Zina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" className={font.className}>
      <body>{children}</body>
    </html>
  )
}
